// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisRestaurant.Infra.Domain;

#nullable disable

namespace SisRestaurant.Infra.Migrations;

[DbContext(typeof(SisRestaurantContext))]
[Migration("20240601221906_AddedUserToRestaurant")]
partial class AddedUserToRestaurant
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Categories.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("Deleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Categories");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Menus.Menu", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("Deleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Menus");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Menus.MenuItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CategoryId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("Deleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("MenuId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.HasIndex("MenuId");

                b.ToTable("MenuItems");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Notifications.Notification", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("Finished")
                    .HasColumnType("bit");

                b.Property<DateTime>("SendAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("Success")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("Notifications");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Payments.Payment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("Deleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<double>("Value")
                    .HasColumnType("float");

                b.HasKey("Id");

                b.ToTable("Payments");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Reservations.Reservation", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("CustomerId")
                    .HasColumnType("int");

                b.Property<bool>("Deleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Details")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("PaymentId")
                    .HasColumnType("int");

                b.Property<DateTime>("ReservedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("RestaurantId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("PaymentId");

                b.HasIndex("RestaurantId");

                b.ToTable("Reservations");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Reservations.ReservationSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("Capacity")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("FinishAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("PaymentRequired")
                    .HasColumnType("bit");

                b.Property<DateTime>("StartAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("ReservationSettings");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Restaurants.Restaurant", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("Deleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MenuId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Open")
                    .HasColumnType("bit");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("SettingsId")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("MenuId");

                b.HasIndex("SettingsId");

                b.HasIndex("UserId");

                b.ToTable("Restaurants");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Users.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("Deleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Users");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Menus.MenuItem", b =>
            {
                b.HasOne("SisRestaurant.Infra.Domain.Categories.Category", "Category")
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SisRestaurant.Infra.Domain.Menus.Menu", null)
                    .WithMany("Items")
                    .HasForeignKey("MenuId");

                b.Navigation("Category");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Reservations.Reservation", b =>
            {
                b.HasOne("SisRestaurant.Infra.Domain.Users.User", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SisRestaurant.Infra.Domain.Payments.Payment", "Payment")
                    .WithMany()
                    .HasForeignKey("PaymentId");

                b.HasOne("SisRestaurant.Infra.Domain.Restaurants.Restaurant", "Restaurant")
                    .WithMany("Reservations")
                    .HasForeignKey("RestaurantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");

                b.Navigation("Payment");

                b.Navigation("Restaurant");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Restaurants.Restaurant", b =>
            {
                b.HasOne("SisRestaurant.Infra.Domain.Menus.Menu", "Menu")
                    .WithMany()
                    .HasForeignKey("MenuId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SisRestaurant.Infra.Domain.Reservations.ReservationSettings", "Settings")
                    .WithMany()
                    .HasForeignKey("SettingsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SisRestaurant.Infra.Domain.Users.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Menu");

                b.Navigation("Settings");

                b.Navigation("User");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Menus.Menu", b =>
            {
                b.Navigation("Items");
            });

        modelBuilder.Entity("SisRestaurant.Infra.Domain.Restaurants.Restaurant", b =>
            {
                b.Navigation("Reservations");
            });
#pragma warning restore 612, 618
    }
}
